name: Normalize App Name
description: Normalize app name to safe directory name

inputs:
  app_name:
    required: true

outputs:
  safe_app:
    description: Normalized app name
    value: ${{ steps.normalize.outputs.safe_app }}

runs:
  using: composite
  steps:
    - id: normalize
      shell: bash
      run: |
        SAFE_APP=$(echo "${{ inputs.app_name }}" | sed 's/[^a-zA-Z0-9_-]/_/g')
        echo "safe_app=$SAFE_APP" >> $GITHUB_OUTPUT
        echo "SAFE_APP=$SAFE_APP" >> $GITHUB_ENV
