name: Generate Android Keystore

inputs:
  overwrite:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - uses: dart-lang/setup-dart@v1

    - shell: bash
      run: |
        ARGS="--ci"
        if [ "${{ inputs.overwrite }}" = "true" ]; then
          ARGS="$ARGS --overwrite"
        fi
        dart generate_keystore.dart $ARGS
